Building the Launch Your Journey Page
dev-launchers/dev-launchers-platform pull request #1638
Opened 2024-01-26 05:15 UTC by rinagobo

1. Created a new folder called "LaunchYourJourney" which has "index.js" / "LaunchYourJourney.js" / "Styled LaunchYourJourney.js" in "modules" folder.

2. Created a new folder called "JourneySection" folder which has  "index.js" / "JourneySection.js" / "Styled JourneySection.js" in the "LaunchYourJourney" folder.

3. Created a new folder called "EmailTemplate" in the "Onboarding" folder in the "Images" folder to store related icons imported for the page.

2024-02-10 16:41 UTC, judeamos commented on apps/user-profile/src/components/modules/LaunchYourJourney/LaunchYourJourney.js
> +                    <img src={insta} style={{padding:"0px 10px"}}/>
Move these styles to a class, in SytledLaunchYourJourney.js. It's better to use classes when a style is going to be reused multiple times. `padding: "0px 10px"` is reused, and so is `colour: "white"`.

2024-02-10 16:43 UTC, judeamos commented on apps/user-profile/src/images/Onboarding/EmailTemplate/creating_templates.png
Name this creating-templates.png, you've followed this naming convention, best to be consistent with it. Reflect this for "powering_profile.png" file name.

2024-02-10 16:45 UTC, judeamos commented on apps/user-profile/src/components/modules/LaunchYourJourney/JourneySection/JourneySection.js
> +                        <Typography type="pLarge" style={{color: "white"}}>{title}</Typography>
Move reused styles to a class.

2024-02-10 16:47 UTC, judeamos commented on apps/user-profile/src/components/modules/LaunchYourJourney/JourneySection/JourneySection.js
> +                        <Button onClick={clickFunction} buttonType="alternative" buttonSize="standard" style={{padding:"3% 5%",width:"70%" ,color: "#7F7E7F"}}>{buttonTitle}</Button>
Move styling to a class. Though this is not reused, having your styling in one location keeps the code clean, and makes debugging easier.

2024-02-10 16:52 UTC, judeamos approved these changes
Make the changes from the comments i've left, then merge the code. Good work 🙌🏾

2024-02-10 16:52 UTC, judeamos commented on apps/user-profile/src/components/modules/LaunchYourJourney/JourneySection/JourneySection.js
I like what you've done here 👍🏾, splitting sections into two, left & right. _No need to make this change_, just a thought — is it possible we could make this component smarter, and have all logic in one function, instead of two?

2024-02-10 16:53 UTC, judeamos commented on apps/user-profile/src/components/modules/LaunchYourJourney/JourneySection/JourneySection.js
I like what you've done here 👍🏾, splitting sections into two, left & right. No need to make this change, just a thought — is it possible we could make this component smarter, and have all logic in one function, instead of two?

2024-02-11 19:38 UTC, judeamos reviewed
test

2024-02-11 19:38 UTC, judeamos commented on apps/user-profile/src/components/modules/LaunchYourJourney/JourneySection/JourneySection.js
I like what you've done here 👍🏾, splitting sections into two, left & right. No need to make this change, just a thought — is it possible we could make this component smarter, and have all logic in one function, instead of two?

2024-02-11 19:45 UTC, rinagobo commented on apps/user-profile/src/images/Onboarding/EmailTemplate/creating_templates.png
Done! (commit 6)

2024-02-11 19:48 UTC, rinagobo commented on apps/user-profile/src/components/modules/LaunchYourJourney/LaunchYourJourney.js
> +    const CreatePage = (e) => {
Done! (Commit 7)

2024-02-11 20:39 UTC, rinagobo commented on apps/user-profile/src/components/modules/LaunchYourJourney/LaunchYourJourney.js
> +                    <Typography style={{color: "white", fontSize: "80px"}}>Launch Your Journey!</Typography>
Done! (Commit 8)

2024-02-11 20:39 UTC, rinagobo commented on apps/user-profile/src/components/modules/LaunchYourJourney/LaunchYourJourney.js
> +                    <img src={insta} style={{padding:"0px 10px"}}/>
Done! (Commit 8)

2024-02-11 20:53 UTC, rinagobo commented on apps/user-profile/src/components/modules/LaunchYourJourney/JourneySection/JourneySection.js
> +                        <Button onClick={clickFunction} buttonType="alternative" buttonSize="standard" style={{padding:"3% 5%",width:"70%" ,color: "#7F7E7F"}}>{buttonTitle}</Button>
Done! (Commit 9)

2024-02-11 20:53 UTC, rinagobo commented on apps/user-profile/src/components/modules/LaunchYourJourney/JourneySection/JourneySection.js
> +                        <Typography type="pLarge" style={{color: "white"}}>{title}</Typography>
Done! (Commit 9)

2024-02-11 21:29 UTC, rinagobo commented on apps/user-profile/src/components/modules/LaunchYourJourney/JourneySection/JourneySection.js
I've created <JourneySection /> component that can set an icon image on the preferred side by passing passing "right" or "left" for the side property. (Commit 10)

Let me know if my logic and code look good to you!

2024-03-07 05:41 UTC, Enjoy2Live requested changes
`packages/tailwind-constructor/tailwind.css` file should be removed otherwise it'll be tracked by git, please remove that file and squash this PR when it's ready @judeamos

2024-04-01 23:51 UTC, Enjoy2Live approved these changes

2024-04-02 01:57 UTC, merged