Mobile device configuration- search results, talent comm pages
dev-launchers/dev-launchers-platform pull request #1742
Opened 2024-03-28 23:04 UTC by ceewa30

[Mobile device configuration- search results, talent comm pages](https://github.com/dev-launchers/dev-launchers-platform/commit/980e70a4f66c30af6559cd21d8aca110cb283a94)

2024-03-30 22:24 UTC, Enjoy2Live commented
tailwind.css file should never be committed, it's even ignored by git so you either are behind master or forcefully committed the file. let's delete it!

2024-04-01 18:30 UTC, ramy-coder approved these changes

2024-04-02 23:21 UTC, Enjoy2Live requested changes
tailwind.css file should never be committed, it's even ignored by git so you either are behind master or forcefully committed the file. let's delete it!

2024-10-07 00:11 UTC, dbradham commented
@Enjoy2Live @ceewa30 @ramy-coder @dev-launchers/dev-recruit is this still being worked on or can it be closed?

2024-11-14 02:35 UTC, closed without merging