Desktop mobile links2
dev-launchers/dev-launchers-platform pull request #782
Opened 2022-12-23 22:07 UTC by alston-hsu

2022-12-28 20:48 UTC, Enjoy2Live requested changes
Looks pretty good, we need to complete those requested changes before we can merge.
They're just coding style related as the component looks almost identical to the Figma.

Thanks @alston-hsu :rocket:

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/index.ts
> +  linkText?: string;
@alston-hsu 
I think these should be: `href` and `text`

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +  ${typographyStyles.pSmall}
@alston-hsu 
I think the typography variant of link isn't yet defined so we have to create these [Typography variants](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1044%3A1054&t=O439lgOvsitp3B4S-4)
![image](https://user-images.githubusercontent.com/27841994/209867963-9584adac-bd45-43f5-8444-cbb25ac171fd.png)
`typographyStyles.pSmall` is a bit different than them

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +    ${typographyStyles.p}
@alston-hsu 
I think the typography variant of link isn't yet defined so we have to create these [Typography variants](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1044%3A1054&t=O439lgOvsitp3B4S-4)
![image](https://user-images.githubusercontent.com/27841994/209867963-9584adac-bd45-43f5-8444-cbb25ac171fd.png)
`typographyStyles.p` is a bit different than them

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +      ${typographyStyles.p}
@alston-hsu 
I think the typography variant of link isn't yet defined so we have to create these [Typography variants](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1044%3A1054&t=O439lgOvsitp3B4S-4)
![image](https://user-images.githubusercontent.com/27841994/209867963-9584adac-bd45-43f5-8444-cbb25ac171fd.png)
`typographyStyles.p` is a bit different than them

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +      ${typographyStyles.p}
@alston-hsu 
I think the typography variant of link isn't yet defined so we have to create these [Typography variants](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1044%3A1054&t=O439lgOvsitp3B4S-4)
![image](https://user-images.githubusercontent.com/27841994/209867963-9584adac-bd45-43f5-8444-cbb25ac171fd.png)
`typographyStyles.p` is a bit different than them

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +    outline: 1px dashed black;
@alston-hsu why are we doing border and outline at the same time here?

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +    border-radius: 4px;
@alston-hsu 
please use `packages/UI/src/components/atoms/Radius/StyledRadius.ts` file to for this radius.

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +      ${typographyStyles.p}
@alston-hsu 
I think the typography variant of link isn't yet defined so we have to create these [Typography variants](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1044%3A1054&t=O439lgOvsitp3B4S-4)
![image](https://user-images.githubusercontent.com/27841994/209867963-9584adac-bd45-43f5-8444-cbb25ac171fd.png)
`typographyStyles.p` is a bit different than them

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +    @media only screen and (min-width: 62.5rem) {
@alston-hsu 
The theme already has breakpoints can you please use the equivalent of this one from the theme?

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +      ${typographyStyles.p}
@alston-hsu 
I think the typography variant of link isn't yet defined so we have to create these [Typography variants](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1044%3A1054&t=O439lgOvsitp3B4S-4)
![image](https://user-images.githubusercontent.com/27841994/209867963-9584adac-bd45-43f5-8444-cbb25ac171fd.png)
`typographyStyles.p` is a bit different than them

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +      ${typographyStyles.p}
@alston-hsu 
I think the typography variant of link isn't yet defined so we have to create these [Typography variants](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1044%3A1054&t=O439lgOvsitp3B4S-4)
![image](https://user-images.githubusercontent.com/27841994/209867963-9584adac-bd45-43f5-8444-cbb25ac171fd.png)
`typographyStyles.p` is a bit different than them

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/StyledLink.ts
> +import theme from '../../../styles/theme';
@alston-hsu 
importing the theme is highly discouraged, please use this approach https://styled-components.com/docs/advanced#function-themes

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/Link.stories.tsx
> +import type { Story, Meta } from '@storybook/react';
@alston-hsu 
`ComponentStory` and `ComponentMeta` should be used here instead. please check other components to see 
the way we used those types

2022-12-28 20:48 UTC, Enjoy2Live commented on packages/UI/src/components/atoms/Link/Link.tsx
> +const Link: FC<LinkProps> = ({ linkTo, linkText }) => {
let's spread the rest of the props as follows `const Link: FC<LinkProps> = {linkTo, linkText, ...props})`
and use it on the StyledLink like this: `<StyledLink href={linkTo} {...props}>{linkText}</StyledLink>`

2022-12-30 20:50 UTC, alston-hsu reviewed
changes added

2023-01-12 12:41 UTC, Enjoy2Live approved these changes

2023-01-12 12:42 UTC, merged

2023-02-25 16:54 UTC, dev-launchers-flux commented
:tada: This PR is included in version 2.10.0 :tada:

The release is available on [GitHub release](https://github.com/dev-launchers/dev-launchers-platform/releases/tag/v2.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: