Alicefate/ add variable to FormField and OpenResponse
dev-launchers/dev-launchers-platform pull request #899
Opened 2023-03-12 19:45 UTC by alicefate

add value to this two component, so it could set default value. 
It is helpful when user edit the exsiting idea, they can have their original input.

2023-03-12 20:26 UTC, alicefate commented
I only changed 4 files. FormField.tsx and index.ts in FormField, OpenResponse.tsx and index.ts in OpenResponse. 
Others are add by systom automaticly.

2023-03-14 21:03 UTC, Enjoy2Live requested changes
@alicefate looks great, I like these small changes because more of them can lead to generalized props.

left you a question in the comments please answer it and consider this merged :D

2023-03-14 23:12 UTC, alicefate commented on packages/UI/src/components/organisms/FormField/FormField.tsx
> -          {label} {required && <span css={{ color: 'red' }}>*</span>}
Compiler can understand better. and it will stop problem warnning.

2023-03-25 15:19 UTC, dbradham commented
@Enjoy2Live can you let Iris know if any more changes are need here or approve?

2023-03-25 15:21 UTC, dbradham commented on packages/UI/src/components/organisms/FormField/FormField.tsx
> -          {label} {required && <span css={{ color: 'red' }}>*</span>}
@alicefate can you revert this change? It seems to be the only pending item for this PR

2023-03-25 21:13 UTC, alicefate commented on packages/UI/src/components/organisms/FormField/FormField.tsx
> -          {label} {required && <span css={{ color: 'red' }}>*</span>}
sure

2023-04-23 06:28 UTC, Enjoy2Live approved these changes
LGTM!

2023-04-23 15:22 UTC, merged

2023-05-27 20:38 UTC, dev-launchers-flux commented
:tada: This PR is included in version 2.11.0 :tada:

The release is available on [GitHub release](https://github.com/dev-launchers/dev-launchers-platform/releases/tag/v2.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: